name: skaffold
version: v0.26.0
summary: Easy and Repeatable Kubernetes Development
description: |
  Skaffold is a command line tool that facilitates continuous development for Kubernetes applications.
  You can iterate on your application source code locally then deploy to local or remote Kubernetes clusters.
  Skaffold handles the workflow for building, pushing and deploying your application. It also provides building blocks and describe customizations for a CI/CD pipeline.
grade: stable
confinement: strict

apps:
  skaffold:
    command: skaffold
    plugs: [home, network, network-bind]
plugs:
  personal-files:
    read: [$HOME/.kube/config, $HOME/.docker/config.json]
parts:
  skaffold:
    plugin: dump
    source: .
    override-build: |
      apt-get install curl -y
      curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.26.0/skaffold-linux-amd64
      chmod +x ./skaffold
      mkdir -p /build/parts/skaffold/install/bin
      mv ./skaffold /build/parts/skaffold/install/bin/.
  git:
    source: https://github.com/git/git
    source-type: git
    source-tag: v2.19.0
    source-depth: 1
    plugin: autotools
    configflags:
      - --with-curl
      - --with-expat
    build-packages:
        - gettext
        - libssl-dev
        - libexpat1-dev
    stage-packages:
        - gettext
        - libcurl3
        - libcurl4-openssl-dev
